In [ ]:
import numpy as np
collection1 = [[1,2,3,4] , [5,6,7,8]]
collection2 = [(1,2,3,4) , (5,6,7,8)]

np_coll_1 = np.array(collection1)
np_coll_2 = np.array(collection2)

print(f'collection1 : \n{np_coll_1}')
print("----------------------")
print(f'collection2 : \n{np_coll_2}')

collection1 :
[[1 2 3 4]
 [5 6 7 8]]
----------------------
collection2 :
[[1 2 3 4]
 [5 6 7 8]]

In [ ]:
arr_1 = np.array([(1,2,3,4,5) , (2,3,4,5,6) , (3,4,5,6,7)])
arr_2 = np.zeros((6,2))
arr_3 = np.zeros_like(arr_1)
arr_4 = np.ones((2,6))
arr_5 = np.ones_like(arr_1)
arr_6 = np.empty((4,2))
arr_7 = np.empty_like(arr_1)
arr_8 = np.arange(10,100,7)
arr_9 = np.linspace(10 , 100 , 7)

print(f'arr_1 : \n{arr_1}')
print("------------")
print(f'arr_2 : \n{arr_2}')
print("------------")
print(f'arr_3 : \n{arr_3}')
print("------------")
print(f'arr_4 : \n{arr_4}')
print("------------")
print(f'arr_5 : \n{arr_5}')
print("------------")
print(f'arr_6 : \n{arr_6}')
print("------------")
print(f'arr_7 : \n{arr_7}')
print("------------")
print(f'arr_8 : \n{arr_8}')
print("------------")
print(f'arr_9 : \n{arr_9}')

arr_1 :
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
------------
arr_2 :
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
------------
arr_3 :
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
------------
arr_4 :
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
------------
arr_5 :
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
------------
arr_6 :
[[4.65216703e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
------------
arr_7 :
[[94160907916416              0              0              0
               0]
 [             0              0              0              0
               0]
 [             0              0              0              0
               0]]
------------
arr_8 :
[10 17 24 31 38 45 52 59 66 73 80 87 94]
------------
arr_9 :
[ 10.  25.  40.  55.  70.  85. 100.]

In [ ]:
import sys
arr_10 = np.reshape(arr_1 , (3 , 1 , 5))
i = np.size(arr_10)
arr_11 = np.reshape(arr_10 , (1,i))
arr_12 = np.arange(100).reshape(10,10)
arr_13 = np.set_printoptions(threshold=sys.maxsize)   # for big data and complete display


print("------------")
print(f'arr_10 : \n{arr_10}')
print("------------")
print(f'arr_11 : \n{arr_11}')
print("------------")
print(f'arr_12 : \n{arr_12}')
print("------------")
print(f'arr_13 : \n{arr_13}')
print("------------")

------------
arr_10 :
[[[1 2 3 4 5]]

 [[2 3 4 5 6]]

 [[3 4 5 6 7]]]
------------
arr_11 :
[[1 2 3 4 5 2 3 4 5 6 3 4 5 6 7]]
------------
arr_12 :
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
------------
arr_13 :
None
------------

In [ ]:
import numpy as np
arr_14 = np.linspace(0,100,30 , endpoint=False).reshape((10,3))
arr_15 = np.cumsum(arr_14)

# sum , max , min with and without axis



print(f'arr_14 : \n{arr_14}')
print("------------")
print(f'arr_15 : \n{arr_15}')
print("------------")

arr_14 :
[[ 0.          3.33333333  6.66666667]
 [10.         13.33333333 16.66666667]
 [20.         23.33333333 26.66666667]
 [30.         33.33333333 36.66666667]
 [40.         43.33333333 46.66666667]
 [50.         53.33333333 56.66666667]
 [60.         63.33333333 66.66666667]
 [70.         73.33333333 76.66666667]
 [80.         83.33333333 86.66666667]
 [90.         93.33333333 96.66666667]]
------------
arr_15 :
[   0.            3.33333333   10.           20.           33.33333333
   50.           70.           93.33333333  120.          150.
  183.33333333  220.          260.          303.33333333  350.
  400.          453.33333333  510.          570.          633.33333333
  700.          770.          843.33333333  920.         1000.
 1083.33333333 1170.         1260.         1353.33333333 1450.        ]
------------

In [ ]:
arr_16 = np.arange(20)
arr_17 = np.arange(20).reshape((4,5))
arr_18 = np.arange(20).reshape((2,2,5))
arr_19 = np.arange(50).reshape((5,10))

print(f' arr_16_1 : \n{arr_16}')
print("---------------------")
print(f' arr_16_2 : \n{arr_16[5]}')
print("---------------------")
print(f' arr_16_3 : \n{arr_16[5:10]}')
print("---------------------")
print(f' arr_16_4 : \n{arr_16[5:10:2]}')
print("---------------------")
print(f' arr_16_5 : \n{arr_16[10:5:-1]}')

print("---------------------")
print("---------------------")
print("---------------------")




print(f'arr_17_1 : \n{arr_17}')
print("---------------------")
print(f'arr_17_2 : \n{arr_17[3,2]}')
print("---------------------")
print(f'arr_17_3 : \n{arr_17[1:3 , :2]}')
print("---------------------")
print(f'arr_17_4 : \n{arr_17[1:3 , :]}')
print("---------------------")
print(f'arr_17_5 : \n{arr_17[: , 0:3]}')


print("---------------------")
print("---------------------")
print("---------------------")



print(f'arr_16_6 : \n{arr_16[-1]}')
print("---------------------")
print(f'arr_17_6 : \n{arr_17[-1]}')

print("---------------------")
print("---------------------")
print("---------------------")



print(f'arr_18_1 : \n{arr_18}')
print("---------------------")
print(f'arr_18_2 : \n{arr_18[1,1,4]}')
print("---------------------")
print(f'arr_18_3 : \n{arr_18[: , :1 , 0:3]}')
print("---------------------")
print(f'arr_18_4 : \n{arr_18[0]}')


print("---------------------")
print("---------------------")
print("---------------------")



print(f'arr_19 : \n{arr_19}')
print("---------------------")

print('arr_19 rows')
for r in arr_19:
  print(r)
  print('*')
print("---------------------")
print('arr_18 elements with more than 15 condition')
for element in arr_18.flat:  
  if element>15 :
    print(element)


print("---------------------")

 arr_16_1 :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
---------------------
 arr_16_2 :
5
---------------------
 arr_16_3 :
[5 6 7 8 9]
---------------------
 arr_16_4 :
[5 7 9]
---------------------
 arr_16_5 :
[10  9  8  7  6]
---------------------
---------------------
---------------------
arr_17_1 :
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
---------------------
arr_17_2 :
17
---------------------
arr_17_3 :
[[ 5  6]
 [10 11]]
---------------------
arr_17_4 :
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
---------------------
arr_17_5 :
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]
 [15 16 17]]
---------------------
---------------------
---------------------
arr_16_6 :
19
---------------------
arr_17_6 :
[15 16 17 18 19]
---------------------
---------------------
---------------------
arr_18_1 :
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
---------------------
arr_18_2 :
19
---------------------
arr_18_3 :
[[[ 0  1  2]]

 [[10 11 12]]]
---------------------
arr_18_4 :
[[0 1 2 3 4]
 [5 6 7 8 9]]
---------------------
---------------------
---------------------
arr_19 :
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
---------------------
arr_19 rows
[0 1 2 3 4 5 6 7 8 9]
*
[10 11 12 13 14 15 16 17 18 19]
*
[20 21 22 23 24 25 26 27 28 29]
*
[30 31 32 33 34 35 36 37 38 39]
*
[40 41 42 43 44 45 46 47 48 49]
*
---------------------
arr_18 elements with more than 15 condition
16
17
18
19
---------------------

In [ ]:
A = [[2,3,4,5,6,7,8],
     [1,2,3,4,5,6,7],
     [4,5,6,7,8,9,10]]
arr_20 = np.array(A)
arr_21 = np.transpose(arr_20)
arr_22 = np.ravel(arr_20)
arr_23 = np.resize(arr_20 , (5,3))
arr_24 = np.resize(arr_20 , (5,3))


print(f'A : \n{A}')
print("------------------")
print(f'arr_20 : \n{arr_19}')
print("------------------")
print(f'arr_21 : \n{arr_20}')
print("------------------")
print(f'arr_22 : \n{arr_22}')
print("------------------")
print(f'arr_23 : \n{arr_23}')
print("------------------")
print(f'arr_24 : \n{arr_24}')
print("------------------")

A :
[[2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7], [4, 5, 6, 7, 8, 9, 10]]
------------------
arr_20 :
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
------------------
arr_21 :
[[ 2  3  4  5  6  7  8]
 [ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]
------------------
arr_22 :
[ 2  3  4  5  6  7  8  1  2  3  4  5  6  7  4  5  6  7  8  9 10]
------------------
arr_23 :
[[2 3 4]
 [5 6 7]
 [8 1 2]
 [3 4 5]
 [6 7 4]]
------------------
arr_24 :
[[2 3 4]
 [5 6 7]
 [8 1 2]
 [3 4 5]
 [6 7 4]]
------------------

In [ ]:
a = np.array([(1,2,3,4,5 ,7),
                   (3,4,5,6,7,9),
                   (5,6,7,8,9,11)])
b = np.array([(1,1,1,1,1,1),
                   (2,2,2,2,2,2),
                   (3,3,3,3,3,3)])

arr_25 = np.hstack((a,b))
arr_26 = np.vstack((a,b))
arr_27 = np.column_stack((a,b))
arr_28 = np.row_stack((a,b))
arr_29 = np.hsplit(arr_28 , 3)






print(f'a : \n{a}')
print("------------------")
print(f'b : \n{b}')
print("------------------")
print(f'arr_25 : \n{arr_25}')
print("------------------")
print(f'arr_26 : \n{arr_26}')
print("------------------")
print(f'arr_27 : \n{arr_27}')
print("------------------")
print(f'arr_28 : \n{arr_28}')
print("------------------")
print(f'arr_29 : \n{arr_29}')
print("------------------")

a :
[[ 1  2  3  4  5  7]
 [ 3  4  5  6  7  9]
 [ 5  6  7  8  9 11]]
------------------
b :
[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]]
------------------
arr_25 :
[[ 1  2  3  4  5  7  1  1  1  1  1  1]
 [ 3  4  5  6  7  9  2  2  2  2  2  2]
 [ 5  6  7  8  9 11  3  3  3  3  3  3]]
------------------
arr_26 :
[[ 1  2  3  4  5  7]
 [ 3  4  5  6  7  9]
 [ 5  6  7  8  9 11]
 [ 1  1  1  1  1  1]
 [ 2  2  2  2  2  2]
 [ 3  3  3  3  3  3]]
------------------
arr_27 :
[[ 1  2  3  4  5  7  1  1  1  1  1  1]
 [ 3  4  5  6  7  9  2  2  2  2  2  2]
 [ 5  6  7  8  9 11  3  3  3  3  3  3]]
------------------
arr_28 :
[[ 1  2  3  4  5  7]
 [ 3  4  5  6  7  9]
 [ 5  6  7  8  9 11]
 [ 1  1  1  1  1  1]
 [ 2  2  2  2  2  2]
 [ 3  3  3  3  3  3]]
------------------
arr_29 :
[array([[1, 2],
       [3, 4],
       [5, 6],
       [1, 1],
       [2, 2],
       [3, 3]]), array([[3, 4],
       [5, 6],
       [7, 8],
       [1, 1],
       [2, 2],
       [3, 3]]), array([[ 5,  7],
       [ 7,  9],
       [ 9, 11],
       [ 1,  1],
       [ 2,  2],
       [ 3,  3]])]
------------------

In [ ]:
D = [[2,3,4,5,6],
     [1,2,3,4,5]]

d = np.array(D)

arr_26 = np.copy(d)
arr_27 = d


print(f'arr_26 : \n{arr_26}')
print("------------------")
print(f'arr_27 : \n{arr_27}')
print("------------------")
print(d is arr_26)
print("------------------")
print(d is arr_27)
print("------------------")

arr_26 :
[[2 3 4 5 6]
 [1 2 3 4 5]]
------------------
arr_27 :
[[2 3 4 5 6]
 [1 2 3 4 5]]
------------------
False
------------------
True
------------------

In [ ]:
x = [2,4,9,1,5,2,7,0]
arr = np.array(x)
arr = np.sort(x)
print(f'arr : \n{arr}')
print("------------------")

arr :
[0 1 2 2 4 5 7 9]
------------------

In [ ]:
import numpy as np
A = np.arange(40).reshape((-1 , 4))
print(f' A : \n{A}')

 A :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]